// Auto-generated by tools/gen_dungeon_proto.mjs — do not edit by hand.
// C ref: dat/dungeon.lua → dungeon.c init_dungeons.

export const DUNGEON_PROTO = Object.freeze([
  {
    "name": "The Dungeons of Doom",
    "bonetag": "D",
    "alignment": "unaligned",
    "themerooms": "themerms.lua",
    "base": 25,
    "range": 5,
    "levels": [
      {
        "name": "rogue",
        "bonetag": "R",
        "flags": [
          "roguelike"
        ],
        "base": 15,
        "range": 4
      },
      {
        "name": "oracle",
        "bonetag": "O",
        "alignment": "neutral",
        "base": 5,
        "range": 5
      },
      {
        "name": "bigrm",
        "bonetag": "B",
        "base": 10,
        "range": 3,
        "chance": 40,
        "nlevels": 13
      },
      {
        "name": "medusa",
        "alignment": "chaotic",
        "base": -5,
        "range": 4,
        "nlevels": 4
      },
      {
        "name": "castle",
        "base": -1
      }
    ],
    "branches": [
      {
        "name": "The Gnomish Mines",
        "base": 2,
        "range": 3
      },
      {
        "name": "Sokoban",
        "chainlevel": "oracle",
        "direction": "up",
        "base": 1
      },
      {
        "name": "The Quest",
        "chainlevel": "oracle",
        "branchtype": "portal",
        "base": 6,
        "range": 2
      },
      {
        "name": "Fort Ludios",
        "branchtype": "portal",
        "base": 18,
        "range": 4
      },
      {
        "name": "Gehennom",
        "chainlevel": "castle",
        "branchtype": "no_down",
        "base": 0
      },
      {
        "name": "The Elemental Planes",
        "branchtype": "no_down",
        "direction": "up",
        "base": 1
      }
    ]
  },
  {
    "name": "Gehennom",
    "bonetag": "G",
    "lvlfill": "hellfill",
    "alignment": "noalign",
    "base": 20,
    "range": 5,
    "flags": [
      "mazelike",
      "hellish"
    ],
    "levels": [
      {
        "name": "valley",
        "bonetag": "V",
        "base": 1
      },
      {
        "name": "sanctum",
        "base": -1
      },
      {
        "name": "juiblex",
        "bonetag": "J",
        "base": 4,
        "range": 4
      },
      {
        "name": "baalz",
        "bonetag": "B",
        "base": 6,
        "range": 4
      },
      {
        "name": "asmodeus",
        "bonetag": "A",
        "base": 2,
        "range": 6
      },
      {
        "name": "wizard1",
        "base": 11,
        "range": 6
      },
      {
        "name": "wizard2",
        "bonetag": "X",
        "chainlevel": "wizard1",
        "base": 1
      },
      {
        "name": "wizard3",
        "bonetag": "Y",
        "chainlevel": "wizard1",
        "base": 2
      },
      {
        "name": "orcus",
        "bonetag": "O",
        "base": 10,
        "range": 6
      },
      {
        "name": "fakewiz1",
        "bonetag": "F",
        "base": -6,
        "range": 4
      },
      {
        "name": "fakewiz2",
        "bonetag": "G",
        "base": -6,
        "range": 4
      }
    ],
    "branches": [
      {
        "name": "Vlad's Tower",
        "direction": "up",
        "base": 9,
        "range": 5
      }
    ]
  },
  {
    "name": "The Gnomish Mines",
    "bonetag": "M",
    "alignment": "lawful",
    "lvlfill": "minefill",
    "base": 8,
    "range": 2,
    "flags": [
      "mazelike"
    ],
    "levels": [
      {
        "name": "minetn",
        "bonetag": "T",
        "flags": [
          "town"
        ],
        "base": 3,
        "range": 2,
        "nlevels": 7
      },
      {
        "name": "minend",
        "base": -1,
        "nlevels": 3
      }
    ]
  },
  {
    "name": "The Quest",
    "bonetag": "Q",
    "base": 5,
    "range": 2,
    "levels": [
      {
        "name": "x-strt",
        "base": 1,
        "range": 1
      },
      {
        "name": "x-loca",
        "bonetag": "L",
        "base": 3,
        "range": 1
      },
      {
        "name": "x-goal",
        "base": -1
      }
    ]
  },
  {
    "name": "Sokoban",
    "alignment": "neutral",
    "base": 4,
    "entry": -1,
    "flags": [
      "mazelike"
    ],
    "levels": [
      {
        "name": "soko1",
        "base": 1,
        "nlevels": 2
      },
      {
        "name": "soko2",
        "base": 2,
        "nlevels": 2
      },
      {
        "name": "soko3",
        "base": 3,
        "nlevels": 2
      },
      {
        "name": "soko4",
        "base": 4,
        "nlevels": 2
      }
    ]
  },
  {
    "name": "Fort Ludios",
    "bonetag": "K",
    "alignment": "unaligned",
    "base": 1,
    "flags": [
      "mazelike"
    ],
    "levels": [
      {
        "name": "knox",
        "bonetag": "K",
        "base": -1
      }
    ]
  },
  {
    "name": "Vlad's Tower",
    "bonetag": "T",
    "protofile": "tower",
    "alignment": "chaotic",
    "base": 3,
    "entry": -1,
    "flags": [
      "mazelike"
    ],
    "levels": [
      {
        "name": "tower1",
        "base": 1
      },
      {
        "name": "tower2",
        "base": 2
      },
      {
        "name": "tower3",
        "base": 3
      }
    ]
  },
  {
    "name": "The Elemental Planes",
    "bonetag": "E",
    "alignment": "unaligned",
    "base": 6,
    "entry": -2,
    "flags": [
      "mazelike"
    ],
    "levels": [
      {
        "name": "astral",
        "base": 1
      },
      {
        "name": "water",
        "base": 2
      },
      {
        "name": "fire",
        "base": 3
      },
      {
        "name": "air",
        "base": 4
      },
      {
        "name": "earth",
        "base": 5
      },
      {
        "name": "dummy",
        "base": 6
      }
    ]
  },
  {
    "name": "The Tutorial",
    "base": 2,
    "flags": [
      "mazelike",
      "unconnected"
    ],
    "levels": [
      {
        "name": "tut-1",
        "base": 1
      },
      {
        "name": "tut-2",
        "base": 2
      }
    ]
  }
]);
