// role_ranks_like_c.js — Per-role experience titles for botl rank_of().
// C ref: role.c roles[] — nine { m, f } rank slots (second string 0 in C → omit **f**).

/** @type {Record<string, Array<{ m: string, f?: string }>>} */
export const ROLE_RANK_TITLES_BY_ABBR = {
    Arc: [
        { m: 'Digger' },
        { m: 'Field Worker' },
        { m: 'Investigator' },
        { m: 'Exhumer' },
        { m: 'Excavator' },
        { m: 'Spelunker' },
        { m: 'Speleologist' },
        { m: 'Collector' },
        { m: 'Curator' },
    ],
    Bar: [
        { m: 'Plunderer', f: 'Plunderess' },
        { m: 'Pillager' },
        { m: 'Bandit' },
        { m: 'Brigand' },
        { m: 'Raider' },
        { m: 'Reaver' },
        { m: 'Slayer' },
        { m: 'Chieftain', f: 'Chieftainess' },
        { m: 'Conqueror', f: 'Conqueress' },
    ],
    Cav: [
        { m: 'Troglodyte' },
        { m: 'Aborigine' },
        { m: 'Wanderer' },
        { m: 'Vagrant' },
        { m: 'Wayfarer' },
        { m: 'Roamer' },
        { m: 'Nomad' },
        { m: 'Rover' },
        { m: 'Pioneer' },
    ],
    Hea: [
        { m: 'Rhizotomist' },
        { m: 'Empiric' },
        { m: 'Embalmer' },
        { m: 'Dresser' },
        { m: 'Medicus ossium', f: 'Medica ossium' },
        { m: 'Herbalist' },
        { m: 'Magister', f: 'Magistra' },
        { m: 'Physician' },
        { m: 'Chirurgeon' },
    ],
    Kni: [
        { m: 'Gallant' },
        { m: 'Esquire' },
        { m: 'Bachelor' },
        { m: 'Sergeant' },
        { m: 'Knight' },
        { m: 'Banneret' },
        { m: 'Chevalier', f: 'Chevaliere' },
        { m: 'Seignieur', f: 'Dame' },
        { m: 'Paladin' },
    ],
    Mon: [
        { m: 'Candidate' },
        { m: 'Novice' },
        { m: 'Initiate' },
        { m: 'Student of Stones' },
        { m: 'Student of Waters' },
        { m: 'Student of Metals' },
        { m: 'Student of Winds' },
        { m: 'Student of Fire' },
        { m: 'Master' },
    ],
    Pri: [
        { m: 'Aspirant' },
        { m: 'Acolyte' },
        { m: 'Adept' },
        { m: 'Priest', f: 'Priestess' },
        { m: 'Curate' },
        { m: 'Canon', f: 'Canoness' },
        { m: 'Lama' },
        { m: 'Patriarch', f: 'Matriarch' },
        { m: 'High Priest', f: 'High Priestess' },
    ],
    Ran: [
        { m: 'Tenderfoot' },
        { m: 'Lookout' },
        { m: 'Trailblazer' },
        { m: 'Reconnoiterer', f: 'Reconnoiteress' },
        { m: 'Scout' },
        { m: 'Arbalester' },
        { m: 'Archer' },
        { m: 'Sharpshooter' },
        { m: 'Marksman', f: 'Markswoman' },
    ],
    Rog: [
        { m: 'Footpad' },
        { m: 'Cutpurse' },
        { m: 'Rogue' },
        { m: 'Pilferer' },
        { m: 'Robber' },
        { m: 'Burglar' },
        { m: 'Filcher' },
        { m: 'Magsman', f: 'Magswoman' },
        { m: 'Thief' },
    ],
    Sam: [
        { m: 'Hatamoto' },
        { m: 'Ronin' },
        { m: 'Ninja', f: 'Kunoichi' },
        { m: 'Joshu' },
        { m: 'Ryoshu' },
        { m: 'Kokushu' },
        { m: 'Daimyo' },
        { m: 'Kuge' },
        { m: 'Shogun' },
    ],
    Tou: [
        { m: 'Rambler' },
        { m: 'Sightseer' },
        { m: 'Excursionist' },
        { m: 'Peregrinator', f: 'Peregrinatrix' },
        { m: 'Traveler' },
        { m: 'Journeyer' },
        { m: 'Voyager' },
        { m: 'Explorer' },
        { m: 'Adventurer' },
    ],
    Val: [
        { m: 'Stripling' },
        { m: 'Skirmisher' },
        { m: 'Fighter' },
        { m: 'Man-at-arms', f: 'Woman-at-arms' },
        { m: 'Warrior' },
        { m: 'Swashbuckler' },
        { m: 'Hero', f: 'Heroine' },
        { m: 'Champion' },
        { m: 'Lord', f: 'Lady' },
    ],
    Wiz: [
        { m: 'Evoker' },
        { m: 'Conjurer' },
        { m: 'Thaumaturge' },
        { m: 'Magician' },
        { m: 'Enchanter', f: 'Enchantress' },
        { m: 'Sorcerer', f: 'Sorceress' },
        { m: 'Necromancer' },
        { m: 'Wizard' },
        { m: 'Mage' },
    ],
};
