// u_init_skill_defs.js — Per-role def_skill tables from u_init.c (NH 5.0).
// C ref: u_init.c Skill_A … Skill_W; weapon.c skill_init() consumes them.

import {
    P_NONE,
    P_DAGGER,
    P_KNIFE,
    P_AXE,
    P_PICK_AXE,
    P_SHORT_SWORD,
    P_BROAD_SWORD,
    P_LONG_SWORD,
    P_TWO_HANDED_SWORD,
    P_SABER,
    P_CLUB,
    P_MACE,
    P_MORNING_STAR,
    P_FLAIL,
    P_HAMMER,
    P_QUARTERSTAFF,
    P_POLEARMS,
    P_SPEAR,
    P_TRIDENT,
    P_LANCE,
    P_BOW,
    P_SLING,
    P_CROSSBOW,
    P_DART,
    P_SHURIKEN,
    P_BOOMERANG,
    P_WHIP,
    P_UNICORN_HORN,
    P_ATTACK_SPELL,
    P_HEALING_SPELL,
    P_DIVINATION_SPELL,
    P_ENCHANTMENT_SPELL,
    P_CLERIC_SPELL,
    P_ESCAPE_SPELL,
    P_MATTER_SPELL,
    P_BARE_HANDED_COMBAT,
    P_TWO_WEAPON_COMBAT,
    P_RIDING,
    P_MARTIAL_ARTS,
    P_BASIC,
    P_SKILLED,
    P_EXPERT,
    P_MASTER,
    P_GRAND_MASTER,
} from './const.js';

/** @typedef {readonly [number, number][]} DefSkillRow */

/** @type {Record<string, DefSkillRow>} */
export const DEF_SKILLS_BY_ABBR = {
    Arc: [
        [P_DAGGER, P_BASIC], [P_KNIFE, P_BASIC], [P_PICK_AXE, P_EXPERT],
        [P_SHORT_SWORD, P_BASIC], [P_SABER, P_EXPERT], [P_CLUB, P_SKILLED],
        [P_QUARTERSTAFF, P_SKILLED], [P_SLING, P_SKILLED], [P_DART, P_BASIC],
        [P_BOOMERANG, P_EXPERT], [P_WHIP, P_EXPERT], [P_UNICORN_HORN, P_SKILLED],
        [P_ATTACK_SPELL, P_BASIC], [P_HEALING_SPELL, P_BASIC],
        [P_DIVINATION_SPELL, P_EXPERT], [P_MATTER_SPELL, P_BASIC],
        [P_RIDING, P_BASIC], [P_TWO_WEAPON_COMBAT, P_BASIC], [P_BARE_HANDED_COMBAT, P_EXPERT],
        [P_NONE, 0],
    ],
    Bar: [
        [P_DAGGER, P_BASIC], [P_AXE, P_EXPERT], [P_PICK_AXE, P_SKILLED],
        [P_SHORT_SWORD, P_EXPERT], [P_BROAD_SWORD, P_SKILLED], [P_LONG_SWORD, P_SKILLED],
        [P_TWO_HANDED_SWORD, P_EXPERT], [P_SABER, P_SKILLED], [P_CLUB, P_SKILLED],
        [P_MACE, P_SKILLED], [P_MORNING_STAR, P_SKILLED], [P_FLAIL, P_BASIC],
        [P_HAMMER, P_EXPERT], [P_QUARTERSTAFF, P_BASIC], [P_SPEAR, P_SKILLED],
        [P_TRIDENT, P_SKILLED], [P_BOW, P_BASIC], [P_ATTACK_SPELL, P_BASIC],
        [P_ESCAPE_SPELL, P_BASIC], [P_RIDING, P_BASIC], [P_TWO_WEAPON_COMBAT, P_BASIC],
        [P_BARE_HANDED_COMBAT, P_MASTER], [P_NONE, 0],
    ],
    Cav: [
        [P_DAGGER, P_BASIC], [P_KNIFE, P_SKILLED], [P_AXE, P_SKILLED], [P_PICK_AXE, P_BASIC],
        [P_CLUB, P_EXPERT], [P_MACE, P_EXPERT], [P_MORNING_STAR, P_BASIC],
        [P_FLAIL, P_SKILLED], [P_HAMMER, P_SKILLED], [P_QUARTERSTAFF, P_EXPERT],
        [P_POLEARMS, P_SKILLED], [P_SPEAR, P_EXPERT], [P_TRIDENT, P_SKILLED],
        [P_BOW, P_SKILLED], [P_SLING, P_EXPERT], [P_ATTACK_SPELL, P_BASIC],
        [P_MATTER_SPELL, P_SKILLED], [P_BOOMERANG, P_EXPERT], [P_UNICORN_HORN, P_BASIC],
        [P_BARE_HANDED_COMBAT, P_MASTER], [P_NONE, 0],
    ],
    Hea: [
        [P_DAGGER, P_SKILLED], [P_KNIFE, P_EXPERT], [P_SHORT_SWORD, P_SKILLED],
        [P_SABER, P_BASIC], [P_CLUB, P_SKILLED], [P_MACE, P_BASIC],
        [P_QUARTERSTAFF, P_EXPERT], [P_POLEARMS, P_BASIC], [P_SPEAR, P_BASIC],
        [P_TRIDENT, P_BASIC], [P_SLING, P_SKILLED], [P_DART, P_EXPERT],
        [P_SHURIKEN, P_SKILLED], [P_UNICORN_HORN, P_EXPERT], [P_HEALING_SPELL, P_EXPERT],
        [P_BARE_HANDED_COMBAT, P_BASIC], [P_NONE, 0],
    ],
    Kni: [
        [P_DAGGER, P_BASIC], [P_KNIFE, P_BASIC], [P_AXE, P_SKILLED], [P_PICK_AXE, P_BASIC],
        [P_SHORT_SWORD, P_SKILLED], [P_BROAD_SWORD, P_SKILLED], [P_LONG_SWORD, P_EXPERT],
        [P_TWO_HANDED_SWORD, P_SKILLED], [P_SABER, P_SKILLED], [P_CLUB, P_BASIC],
        [P_MACE, P_SKILLED], [P_MORNING_STAR, P_SKILLED], [P_FLAIL, P_BASIC],
        [P_HAMMER, P_BASIC], [P_POLEARMS, P_SKILLED], [P_SPEAR, P_SKILLED],
        [P_TRIDENT, P_BASIC], [P_LANCE, P_EXPERT], [P_BOW, P_BASIC],
        [P_CROSSBOW, P_SKILLED], [P_ATTACK_SPELL, P_SKILLED], [P_HEALING_SPELL, P_SKILLED],
        [P_CLERIC_SPELL, P_SKILLED], [P_RIDING, P_EXPERT], [P_TWO_WEAPON_COMBAT, P_SKILLED],
        [P_BARE_HANDED_COMBAT, P_EXPERT], [P_NONE, 0],
    ],
    Mon: [
        [P_QUARTERSTAFF, P_BASIC], [P_SPEAR, P_BASIC], [P_CROSSBOW, P_BASIC],
        [P_SHURIKEN, P_BASIC], [P_ATTACK_SPELL, P_BASIC], [P_HEALING_SPELL, P_EXPERT],
        [P_DIVINATION_SPELL, P_BASIC], [P_ENCHANTMENT_SPELL, P_BASIC],
        [P_CLERIC_SPELL, P_SKILLED], [P_ESCAPE_SPELL, P_SKILLED], [P_MATTER_SPELL, P_BASIC],
        [P_MARTIAL_ARTS, P_GRAND_MASTER], [P_NONE, 0],
    ],
    Pri: [
        [P_CLUB, P_EXPERT], [P_MACE, P_EXPERT], [P_MORNING_STAR, P_EXPERT],
        [P_FLAIL, P_EXPERT], [P_HAMMER, P_EXPERT], [P_QUARTERSTAFF, P_EXPERT],
        [P_POLEARMS, P_SKILLED], [P_SPEAR, P_SKILLED], [P_TRIDENT, P_SKILLED],
        [P_LANCE, P_BASIC], [P_BOW, P_BASIC], [P_SLING, P_BASIC], [P_CROSSBOW, P_BASIC],
        [P_DART, P_BASIC], [P_SHURIKEN, P_BASIC], [P_BOOMERANG, P_BASIC],
        [P_UNICORN_HORN, P_SKILLED], [P_HEALING_SPELL, P_EXPERT],
        [P_DIVINATION_SPELL, P_EXPERT], [P_CLERIC_SPELL, P_EXPERT],
        [P_BARE_HANDED_COMBAT, P_BASIC], [P_NONE, 0],
    ],
    Rog: [
        [P_DAGGER, P_EXPERT], [P_KNIFE, P_EXPERT], [P_SHORT_SWORD, P_EXPERT],
        [P_BROAD_SWORD, P_SKILLED], [P_LONG_SWORD, P_SKILLED], [P_TWO_HANDED_SWORD, P_BASIC],
        [P_SABER, P_SKILLED], [P_CLUB, P_SKILLED], [P_MACE, P_SKILLED],
        [P_MORNING_STAR, P_BASIC], [P_FLAIL, P_BASIC], [P_HAMMER, P_BASIC],
        [P_POLEARMS, P_BASIC], [P_SPEAR, P_BASIC], [P_CROSSBOW, P_EXPERT],
        [P_DART, P_EXPERT], [P_SHURIKEN, P_SKILLED], [P_DIVINATION_SPELL, P_SKILLED],
        [P_ESCAPE_SPELL, P_SKILLED], [P_MATTER_SPELL, P_SKILLED], [P_RIDING, P_BASIC],
        [P_TWO_WEAPON_COMBAT, P_EXPERT], [P_BARE_HANDED_COMBAT, P_EXPERT], [P_NONE, 0],
    ],
    Ran: [
        [P_DAGGER, P_EXPERT], [P_KNIFE, P_SKILLED], [P_AXE, P_SKILLED], [P_PICK_AXE, P_BASIC],
        [P_SHORT_SWORD, P_BASIC], [P_MORNING_STAR, P_BASIC], [P_FLAIL, P_SKILLED],
        [P_HAMMER, P_BASIC], [P_QUARTERSTAFF, P_BASIC], [P_POLEARMS, P_SKILLED],
        [P_SPEAR, P_EXPERT], [P_TRIDENT, P_BASIC], [P_BOW, P_EXPERT], [P_SLING, P_EXPERT],
        [P_CROSSBOW, P_EXPERT], [P_DART, P_EXPERT], [P_SHURIKEN, P_SKILLED],
        [P_BOOMERANG, P_EXPERT], [P_WHIP, P_BASIC], [P_HEALING_SPELL, P_BASIC],
        [P_DIVINATION_SPELL, P_EXPERT], [P_ESCAPE_SPELL, P_BASIC], [P_RIDING, P_BASIC],
        [P_BARE_HANDED_COMBAT, P_BASIC], [P_NONE, 0],
    ],
    Sam: [
        [P_DAGGER, P_BASIC], [P_KNIFE, P_SKILLED], [P_SHORT_SWORD, P_EXPERT],
        [P_BROAD_SWORD, P_SKILLED], [P_LONG_SWORD, P_EXPERT], [P_TWO_HANDED_SWORD, P_EXPERT],
        [P_SABER, P_BASIC], [P_FLAIL, P_SKILLED], [P_QUARTERSTAFF, P_BASIC],
        [P_POLEARMS, P_SKILLED], [P_SPEAR, P_SKILLED], [P_LANCE, P_SKILLED],
        [P_BOW, P_EXPERT], [P_SHURIKEN, P_EXPERT], [P_ATTACK_SPELL, P_BASIC],
        [P_DIVINATION_SPELL, P_BASIC], [P_CLERIC_SPELL, P_SKILLED], [P_RIDING, P_SKILLED],
        [P_TWO_WEAPON_COMBAT, P_EXPERT], [P_MARTIAL_ARTS, P_MASTER], [P_NONE, 0],
    ],
    Tou: [
        [P_DAGGER, P_EXPERT], [P_KNIFE, P_SKILLED], [P_AXE, P_BASIC], [P_PICK_AXE, P_BASIC],
        [P_SHORT_SWORD, P_EXPERT], [P_BROAD_SWORD, P_BASIC], [P_LONG_SWORD, P_BASIC],
        [P_TWO_HANDED_SWORD, P_BASIC], [P_SABER, P_SKILLED], [P_MACE, P_BASIC],
        [P_MORNING_STAR, P_BASIC], [P_FLAIL, P_BASIC], [P_HAMMER, P_BASIC],
        [P_QUARTERSTAFF, P_BASIC], [P_POLEARMS, P_BASIC], [P_SPEAR, P_BASIC],
        [P_TRIDENT, P_BASIC], [P_LANCE, P_BASIC], [P_BOW, P_BASIC], [P_SLING, P_BASIC],
        [P_CROSSBOW, P_BASIC], [P_DART, P_EXPERT], [P_SHURIKEN, P_BASIC],
        [P_BOOMERANG, P_BASIC], [P_WHIP, P_BASIC], [P_UNICORN_HORN, P_SKILLED],
        [P_DIVINATION_SPELL, P_BASIC], [P_ENCHANTMENT_SPELL, P_BASIC],
        [P_ESCAPE_SPELL, P_SKILLED], [P_RIDING, P_BASIC], [P_TWO_WEAPON_COMBAT, P_SKILLED],
        [P_BARE_HANDED_COMBAT, P_SKILLED], [P_NONE, 0],
    ],
    Val: [
        [P_DAGGER, P_EXPERT], [P_AXE, P_EXPERT], [P_PICK_AXE, P_SKILLED],
        [P_SHORT_SWORD, P_SKILLED], [P_BROAD_SWORD, P_SKILLED], [P_LONG_SWORD, P_EXPERT],
        [P_TWO_HANDED_SWORD, P_EXPERT], [P_SABER, P_BASIC], [P_HAMMER, P_EXPERT],
        [P_QUARTERSTAFF, P_BASIC], [P_POLEARMS, P_SKILLED], [P_SPEAR, P_EXPERT],
        [P_TRIDENT, P_BASIC], [P_LANCE, P_SKILLED], [P_SLING, P_BASIC],
        [P_ATTACK_SPELL, P_BASIC], [P_ESCAPE_SPELL, P_BASIC], [P_RIDING, P_SKILLED],
        [P_TWO_WEAPON_COMBAT, P_SKILLED], [P_BARE_HANDED_COMBAT, P_EXPERT], [P_NONE, 0],
    ],
    Wiz: [
        [P_DAGGER, P_EXPERT], [P_KNIFE, P_SKILLED], [P_AXE, P_SKILLED],
        [P_SHORT_SWORD, P_BASIC], [P_CLUB, P_SKILLED], [P_MACE, P_BASIC],
        [P_QUARTERSTAFF, P_EXPERT], [P_POLEARMS, P_SKILLED], [P_SPEAR, P_BASIC],
        [P_TRIDENT, P_BASIC], [P_SLING, P_SKILLED], [P_DART, P_EXPERT],
        [P_SHURIKEN, P_BASIC], [P_ATTACK_SPELL, P_EXPERT], [P_HEALING_SPELL, P_SKILLED],
        [P_DIVINATION_SPELL, P_EXPERT], [P_ENCHANTMENT_SPELL, P_SKILLED],
        [P_CLERIC_SPELL, P_SKILLED], [P_ESCAPE_SPELL, P_EXPERT], [P_MATTER_SPELL, P_EXPERT],
        [P_RIDING, P_BASIC], [P_BARE_HANDED_COMBAT, P_BASIC], [P_NONE, 0],
    ],
};

/**
 * Role special spell → spell school (objects.h SPELL oc_skill), for
 * weapon.c unrestrict_weapon_skill(spell_skilltype(urole.spelspec)).
 * C ref: role.c roles[].spelspec + objects.h.
 */
export const ROLE_SPESPEC_SCHOOL = {
    Arc: P_DIVINATION_SPELL, /* SPE_MAGIC_MAPPING */
    Bar: P_ESCAPE_SPELL, /* SPE_HASTE_SELF */
    Cav: P_MATTER_SPELL, /* SPE_DIG */
    Hea: P_HEALING_SPELL, /* SPE_CURE_SICKNESS */
    Kni: P_CLERIC_SPELL, /* SPE_TURN_UNDEAD */
    Mon: P_HEALING_SPELL, /* SPE_RESTORE_ABILITY */
    Pri: P_CLERIC_SPELL, /* SPE_REMOVE_CURSE */
    Rog: P_DIVINATION_SPELL, /* SPE_DETECT_TREASURE */
    Ran: P_ESCAPE_SPELL, /* SPE_INVISIBILITY */
    Sam: P_DIVINATION_SPELL, /* SPE_CLAIRVOYANCE */
    Tou: P_ENCHANTMENT_SPELL, /* SPE_CHARM_MONSTER */
    Val: P_ATTACK_SPELL, /* SPE_CONE_OF_COLD */
    Wiz: P_ATTACK_SPELL, /* SPE_MAGIC_MISSILE */
};
