#!/usr/bin/env python3
"""Extract nethack-c/upstream/dat/dungeon.lua → js/generated/dungeon_data.js.

Temporary scaffold: structure only (no RNG). C's init_dungeons consumes this
via nhl_loadlua; we feed the same tables to js/dungeon.js until a Lua 5.4 VM
loads dungeon.lua directly.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "nethack-c/upstream/dat/dungeon.lua"
OUT = ROOT / "js/generated/dungeon_data.js"


def strip_lua_comments(text: str) -> str:
    out = []
    i = 0
    n = len(text)
    while i < n:
        if text.startswith("--", i):
            # skip to EOL (no long-comment support needed for dungeon.lua)
            while i < n and text[i] != "\n":
                i += 1
            continue
        out.append(text[i])
        i += 1
    return "".join(out)


class Parser:
    def __init__(self, s: str):
        self.s = s
        self.i = 0

    def skip(self) -> None:
        while self.i < len(self.s) and self.s[self.i].isspace():
            self.i += 1

    def peek(self) -> str:
        self.skip()
        return self.s[self.i] if self.i < len(self.s) else ""

    def eat(self, ch: str) -> None:
        self.skip()
        if self.i >= len(self.s) or self.s[self.i] != ch:
            raise ValueError(f"expected {ch!r} at {self.i}")
        self.i += 1

    def parse_string(self) -> str:
        self.skip()
        q = self.s[self.i]
        assert q in "\"'"
        self.i += 1
        start = self.i
        while self.i < len(self.s) and self.s[self.i] != q:
            if self.s[self.i] == "\\":
                self.i += 2
            else:
                self.i += 1
        val = self.s[start : self.i]
        self.i += 1
        return bytes(val, "utf-8").decode("unicode_escape") if "\\" in val else val

    def parse_number(self) -> int:
        self.skip()
        m = re.match(r"-?\d+", self.s[self.i :])
        if not m:
            raise ValueError(f"number at {self.i}")
        self.i += m.end()
        return int(m.group(0))

    def parse_ident(self) -> str:
        self.skip()
        m = re.match(r"[A-Za-z_][A-Za-z0-9_]*", self.s[self.i :])
        if not m:
            raise ValueError(f"ident at {self.i}")
        self.i += m.end()
        return m.group(0)

    def parse_value(self):
        c = self.peek()
        if c in "\"'":
            return self.parse_string()
        if c == "{" or c == "":
            return self.parse_table()
        if c == "-" or c.isdigit():
            return self.parse_number()
        ident = self.parse_ident()
        if ident == "true":
            return True
        if ident == "false":
            return False
        if ident == "nil":
            return None
        raise ValueError(f"unexpected ident {ident!r}")

    def parse_table(self):
        self.eat("{")
        # Detect array vs map by first entry style
        arr: list = []
        obj: dict = {}
        is_map = None
        while True:
            c = self.peek()
            if c == "}":
                self.eat("}")
                break
            # key = value  OR  value
            # Lookahead: ident/string followed by '=' → map entry
            save = self.i
            key = None
            try:
                if self.peek() in "\"'":
                    maybe_key = self.parse_string()
                else:
                    maybe_key = self.parse_ident()
                self.skip()
                if self.peek() == "=":
                    self.eat("=")
                    key = maybe_key
                    is_map = True
                else:
                    self.i = save
            except ValueError:
                self.i = save

            val = self.parse_value()
            if key is not None:
                obj[key] = val
            else:
                if is_map is None:
                    is_map = False
                arr.append(val)

            c = self.peek()
            if c == ",":
                self.eat(",")
                continue
            if c == "}":
                continue
            raise ValueError(f"expected , or }} at {self.i}")

        if is_map:
            return obj
        return arr


def main() -> int:
    text = strip_lua_comments(SRC.read_text())
    # find "dungeon = "
    m = re.search(r"\bdungeon\s*=", text)
    if not m:
        print("no dungeon =", file=sys.stderr)
        return 1
    p = Parser(text[m.end() :])
    dungeon = p.parse_value()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(dungeon, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/extract-dungeon.py — do not edit.\n"
        "// Source: nethack-c/upstream/dat/dungeon.lua\n"
        f"export const dungeonProto = {body};\n"
    )
    print(f"wrote {OUT} ({len(dungeon)} dungeons)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
