#!/usr/bin/env node
/**
 * Generate js/obj_oc_material_data.js from upstream objects.h (OBJECTS_INIT).
 * C ref: objects.h BITS(..., mtrl, sub) → objects[].oc_material.
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const includeDir = join(root, 'nethack-c/upstream/include');

const MAT_NAMES = [
    'LIQUID', 'WAX', 'VEGGY', 'FLESH', 'PAPER', 'CLOTH', 'LEATHER', 'WOOD', 'BONE',
    'DRAGON_HIDE', 'IRON', 'METAL', 'COPPER', 'SILVER', 'GOLD', 'PLATINUM', 'MITHRIL',
    'PLASTIC', 'GLASS', 'GEMSTONE', 'MINERAL',
];
const matMap = {
    LIQUID: 1, WAX: 2, VEGGY: 3, FLESH: 4, PAPER: 5, CLOTH: 6, LEATHER: 7, WOOD: 8,
    BONE: 9, DRAGON_HIDE: 10, IRON: 11, METAL: 12, COPPER: 13, SILVER: 14, GOLD: 15,
    PLATINUM: 16, MITHRIL: 17, PLASTIC: 18, GLASS: 19, GEMSTONE: 20, MINERAL: 21,
};

const matAlt = MAT_NAMES.join('|');
/* C cpp may emit `, IRON, P_*` or `IRON, P_*` when material wraps to next line. */
const re = new RegExp(`(?:^|,)\\s*(${matAlt})\\s*,\\s*(-?P_[A-Z0-9_]+|0)\\s*,`);

let cpp = execSync(
    `cd "${includeDir}" && printf '%s\\n' '#define OBJECTS_INIT' '#include "objects.h"' | cpp -I. -I.. 2>/dev/null`,
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
);
/* Drop # linemarkers so split parts are not broken mid-struct. */
cpp = cpp.replace(/^#.*$/gm, '');
const parts = cpp.split('{ 0, 0, (char *) 0,');
const mats = [0];
for (let i = 1; i < parts.length; i++) {
    const m = parts[i].match(re);
    mats.push(m ? (matMap[m[1]] ?? 0) : 0);
}

const outPath = join(root, 'js/obj_oc_material_data.js');
const body = `// Auto-generated by tools/gen_obj_oc_material.mjs — do not edit by hand.
// C ref: objects.h OBJECTS_INIT — oc_material (BITS mtrl field).

/** @type {readonly number[]} */
export const OC_MATERIAL_BY_OTYP = Object.freeze(${JSON.stringify(mats)});

/** C: objects[otyp].oc_material */
export function objectOcMaterial(otyp) {
    const a = OC_MATERIAL_BY_OTYP;
    const i = otyp | 0;
    if (i < 0 || i >= a.length) return 0;
    return a[i] | 0;
}
`;
writeFileSync(outPath, body, 'utf8');
console.log(`Wrote ${outPath} (${mats.length} entries)`);
