#!/usr/bin/env node
/**
 * Generate js/obj_oc_weight_data.js from upstream objects.h (OBJECTS_INIT).
 * C ref: objects.c — `objects[otyp].oc_weight` (OBJECT macro `wt` field).
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const includeDir = join(root, 'nethack-c/upstream/include');

function parseWeightExpr(raw) {
    const s = String(raw).replace(/\s+/g, '');
    if (!s) return 0;
    if (/^\d+$/.test(s)) return parseInt(s, 10);
    if (!/^[\d+\-*/]+$/.test(s)) return NaN;
    return Function(`"use strict"; return (${s})`)();
}

function extractWeightsFromCpp(cpp) {
    const cleaned = cpp.replace(/^#[^\n]*\n/gm, '');
    const parts = cleaned.split('{ 0, 0, (char *) 0,');
    const re =
        /_CLASS\s*,\s*[^,]*,\s*[^,]*,\s*(-?\d+)\s*,\s*(\d+)\s*,\s*([^,]+)\s*,/;
    const weights = [];
    for (let i = 1; i < parts.length; i++) {
        const m = parts[i].match(re);
        if (!m) {
            throw new Error(`gen_obj_oc_weight: no class match in object block ${i}`);
        }
        const w = parseWeightExpr(m[2]);
        if (!Number.isFinite(w)) {
            throw new Error(`gen_obj_oc_weight: bad wt expr ${JSON.stringify(m[2])} in block ${i}`);
        }
        weights.push(w | 0);
    }
    return weights;
}

const cpp = execSync(
    `cd "${includeDir}" && printf '%s\\n' '#define OBJECTS_INIT' '#include "objects.h"' | cpp -I. -I.. 2>/dev/null`,
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
);
const weights = extractWeightsFromCpp(cpp);

const outPath = join(root, 'js/obj_oc_weight_data.js');
const body = `// Auto-generated by tools/gen_obj_oc_weight.mjs from nethack-c/upstream/include/objects.h (OBJECTS_INIT).
// C ref: objects.c — \`objects[otyp].oc_weight\` initializer field.
/** @type {readonly number[]} */
export const OC_WEIGHT_BY_OTYP = Object.freeze(${JSON.stringify(weights)});

/** C: objects[].oc_weight — \`otyp\` index matches \`objects_nums\`. */
export function objectOcWeight(otyp) {
    const a = OC_WEIGHT_BY_OTYP;
    const i = otyp | 0;
    if (i < 0 || i >= a.length) return 0;
    return a[i] | 0;
}

/** C: mkobj.c weight — unit weight × quan (floor \`owt\` when already set). */
export function objectStackWeightLikeC(obj) {
    if (!obj) return 0;
    const quan = obj.quan | 0;
    if (quan <= 0) return 0;
    const owt = obj.owt | 0;
    const unit = objectOcWeight(obj.otyp | 0);
    if (unit > 0) return unit * quan;
    if (owt > 0) return owt;
    return quan <= 1 ? 1 : (quan + 1) >> 1;
}
`;
writeFileSync(outPath, body, 'utf8');
console.log(`Wrote ${outPath} (${weights.length} entries, LARGE_BOX=${weights[215]})`);
