#!/usr/bin/env node
/**
 * Regenerate js/role_quest_pm.js — C role.c quest leader/guard/nem PM indices + mflags2 gender.
 * C refs: role.c roles[] (PM_* after home strings), monsters.h MON blocks, role_init quest_status.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const roleC = readFileSync(join(root, 'nethack-c/upstream/src/role.c'), 'utf8');
const monstersH = readFileSync(join(root, 'nethack-c/upstream/include/monsters.h'), 'utf8');

/** @type {string[]} */
const monBlocks = [];
for (const m of monstersH.matchAll(/\bMON\s*\(/g)) {
    let depth = 0;
    let i = m.index + m[0].length - 1;
    while (i < monstersH.length) {
        if (monstersH[i] === '(') depth++;
        else if (monstersH[i] === ')') {
            depth--;
            if (depth === 0) {
                monBlocks.push(monstersH.slice(m.index, i + 1));
                break;
            }
        }
        i++;
    }
}

/** @type {Record<string, number>} */
const pmNameToIdx = {};
for (let i = 0; i < monBlocks.length; i++) {
    const tag = monBlocks[i].match(/,\s*([A-Z][A-Z0-9_]*)\s*\)\s*$/);
    if (tag) pmNameToIdx[tag[1]] = i;
}

/** @param {string} block */
function m2GenderBits(block) {
    let m2 = 0;
    if (block.includes('M2_NEUTER')) m2 |= 0x00040000;
    if (block.includes('M2_FEMALE')) m2 |= 0x00020000;
    if (block.includes('M2_MALE')) m2 |= 0x00010000;
    return m2;
}

/** @type {Record<number, number>} */
const pmIdxToM2Gender = {};
for (let i = 0; i < monBlocks.length; i++) {
    pmIdxToM2Gender[i] = m2GenderBits(monBlocks[i]);
}

const roleRe =
    /"([A-Za-z]{3})",\s*\n\s*"[^"]*",\s*\n\s*"[^"]*",\s*\n\s*(PM_\w+|NON_PM),\s*(?:PM_\w+|NON_PM)(?:\s*\/\*[^*]*\*\/)?,\s*(PM_\w+|NON_PM),\s*(PM_\w+|NON_PM),\s*(PM_\w+|NON_PM)/g;

/** @type {{ abbr: string, mnum: number, ldr: number, guard: number, nem: number }[]} */
const questRows = [];
let m;
while ((m = roleRe.exec(roleC))) {
    const toPm = (tok) => {
        if (tok === 'NON_PM') return -1;
        const key = tok.replace(/^PM_/, '');
        return pmNameToIdx[key] ?? -1;
    };
    questRows.push({
        abbr: m[1],
        mnum: toPm(m[2]),
        ldr: toPm(m[3]),
        guard: toPm(m[4]),
        nem: toPm(m[5]),
    });
}

const out = `// role_quest_pm.js — generated by tools/gen_role_quest_pm.mjs (do not edit by hand).
// C: role.c roles[] quest PM indices; monsters.h M2_MALE|M2_FEMALE|M2_NEUTER for role_init ldrgend/nemgend.

/** @type {Record<string, { mnum: number, ldr: number, guard: number, nem: number }>} */
export const ROLE_QUEST_PM_BY_ABBR = ${JSON.stringify(Object.fromEntries(questRows.map((r) => [r.abbr, r])), null, 2)};

/** @type {number[]} */
export const PM_M2_GENDER_BITS = ${JSON.stringify(pmIdxToM2Gender)};
`;

writeFileSync(join(root, 'js/role_quest_pm.js'), out);
console.log(`wrote js/role_quest_pm.js (${questRows.length} roles, ${monBlocks.length} mons)`);
