#!/usr/bin/env node
/**
 * Generate js/obj_oc_cost_data.js from upstream objects.h (OBJECTS_INIT).
 * C ref: objects.c objects[] — field oc_cost matches OBJECT macro `cost` parameter order.
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const includeDir = join(root, 'nethack-c/upstream/include');

function parseCostExpr(raw) {
    const s = String(raw).replace(/\s+/g, '');
    if (!s) return 0;
    if (/^\d+$/.test(s)) return parseInt(s, 10);
    if (!/^[\d+\-*/]+$/.test(s)) return NaN;
    return Function(`"use strict"; return (${s})`)();
}

function extractCostsFromCpp(cpp) {
    const cleaned = cpp.replace(/^#[^\n]*\n/gm, '');
    const parts = cleaned.split('{ 0, 0, (char *) 0,');
    const re =
        /\b(ILLOBJ|WEAPON|ARMOR|RING|AMULET|TOOL|FOOD|POTION|SCROLL|SPBOOK|WAND|COIN|GEM|ROCK|BALL|CHAIN|VENOM)_CLASS\s*,\s*([^,]+)\s*,\s*([^,]+)\s*,\s*(-?\d+)\s*,\s*(\d+)\s*,\s*([^,]+)\s*,/;
    const costs = [];
    for (let i = 1; i < parts.length; i++) {
        const m = parts[i].match(re);
        if (!m) {
            throw new Error(`gen_obj_oc_cost: no class match in object block ${i}`);
        }
        const c = parseCostExpr(m[6]);
        if (!Number.isFinite(c)) {
            throw new Error(`gen_obj_oc_cost: bad cost expr ${JSON.stringify(m[6])} in block ${i}`);
        }
        costs.push(c | 0);
    }
    return costs;
}

let cpp = execSync(
    `cd "${includeDir}" && printf '%s\\n' '#define OBJECTS_INIT' '#include "objects.h"' | cpp -I. -I.. 2>/dev/null`,
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
);
const costs = extractCostsFromCpp(cpp);

const outPath = join(root, 'js/obj_oc_cost_data.js');
const body = `// Auto-generated by tools/gen_obj_oc_cost.mjs from nethack-c/upstream/include/objects.h (OBJECTS_INIT).
// C ref: objects.c — \`objects[otyp].oc_cost\` initializer field.
/** @type {readonly number[]} */
export const OC_COST_BY_OTYP = Object.freeze(${JSON.stringify(costs)});

/** C: objects[].oc_cost — \`otyp\` index matches \`objects_nums\`. */
export function objectOcCost(otyp) {
    const a = OC_COST_BY_OTYP;
    const i = otyp | 0;
    if (i < 0 || i >= a.length) return 0;
    return a[i] | 0;
}
`;
writeFileSync(outPath, body, 'utf8');
console.log(`Wrote ${outPath} (${costs.length} entries)`);
