#!/usr/bin/env node
/**
 * Generate js/dungeon_proto.js from upstream dat/dungeon.lua.
 * C ref: dungeon.c init_dungeons / init_dungeon_dungeons / init_dungeon_levels.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const luaPath = join(root, 'nethack-c/upstream/dat/dungeon.lua');

/** @param {string} block */
function parseFields(block) {
    /** @type {Record<string, string|number|string[]>} */
    const o = {};
    const nameM = block.match(/name\s*=\s*"([^"]+)"/);
    if (nameM) o.name = nameM[1];
    for (const m of block.matchAll(/(\w+)\s*=\s*"([^"]+)"/g)) {
        if (m[1] === 'name') continue;
        o[m[1]] = m[2];
    }
    for (const m of block.matchAll(/(\w+)\s*=\s*(-?\d+)/g)) {
        o[m[1]] = parseInt(m[2], 10);
    }
    const flagsArr = block.match(/flags\s*=\s*\{\s*([^}]+)\}/);
    if (flagsArr) {
        o.flags = flagsArr[1].split(',').map((s) => s.trim().replace(/"/g, '')).filter(Boolean);
    } else {
        const flagsStr = block.match(/flags\s*=\s*"([^"]+)"/);
        if (flagsStr) o.flags = [flagsStr[1]];
    }
    return o;
}

/** @param {string} section */
function parseSubTables(section, key) {
    const re = new RegExp(`${key}\\s*=\\s*\\{`, 'g');
    const m = re.exec(section);
    if (!m) return [];
    let i = m.index + m[0].length;
    let depth = 1;
    const start = i;
    while (i < section.length && depth > 0) {
        if (section[i] === '{') depth++;
        else if (section[i] === '}') depth--;
        i++;
    }
    const inner = section.slice(start, i - 1);
    /** @type {string[]} */
    const blocks = [];
    let j = 0;
    while (j < inner.length) {
        const open = inner.indexOf('{', j);
        if (open < 0) break;
        let d = 1;
        let k = open + 1;
        while (k < inner.length && d > 0) {
            if (inner[k] === '{') d++;
            else if (inner[k] === '}') d--;
            k++;
        }
        blocks.push(inner.slice(open, k));
        j = k;
    }
    return blocks.map(parseFields);
}

const raw = readFileSync(luaPath, 'utf8').replace(/--[^\n]*/g, '');
const topStart = raw.indexOf('dungeon = {');
if (topStart < 0) throw new Error('dungeon = { not found');
let i = topStart + 'dungeon = {'.length;
let depth = 1;
const start = i;
while (i < raw.length && depth > 0) {
    if (raw[i] === '{') depth++;
    else if (raw[i] === '}') depth--;
    i++;
}
const topInner = raw.slice(start, i - 1);

/** @type {string[]} */
const dungeonBlocks = [];
let j = 0;
while (j < topInner.length) {
    const open = topInner.indexOf('{', j);
    if (open < 0) break;
    let d = 1;
    let k = open + 1;
    while (k < topInner.length && d > 0) {
        if (topInner[k] === '{') d++;
        else if (topInner[k] === '}') d--;
        k++;
    }
    dungeonBlocks.push(topInner.slice(open, k));
    j = k;
}

function parseDungeonBlock(block) {
    const levelsIdx = block.search(/\blevels\s*=/);
    const branchesIdx = block.search(/\bbranches\s*=/);
    const headerEnd = Math.min(
        levelsIdx >= 0 ? levelsIdx : block.length,
        branchesIdx >= 0 ? branchesIdx : block.length,
    );
    const d = parseFields(block.slice(0, headerEnd));
    if (levelsIdx >= 0) d.levels = parseSubTables(block, 'levels');
    if (branchesIdx >= 0) d.branches = parseSubTables(block, 'branches');
    return d;
}

const dungeons = dungeonBlocks.map(parseDungeonBlock);

const outPath = join(root, 'js/dungeon_proto.js');
const body = `// Auto-generated by tools/gen_dungeon_proto.mjs — do not edit by hand.
// C ref: dat/dungeon.lua → dungeon.c init_dungeons.

export const DUNGEON_PROTO = Object.freeze(${JSON.stringify(dungeons, null, 2)});
`;
writeFileSync(outPath, body, 'utf8');
console.log(`Wrote ${outPath} (${dungeons.length} dungeons)`);
