#!/usr/bin/env node
/**
 * Generate js/obj_oc_damage_data.js from upstream objects.h (OBJECTS_INIT).
 * C ref: objects.c objects[] — oc_wsdam / oc_wldam (OBJECT macro sdam, ldam).
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const includeDir = join(root, 'nethack-c/upstream/include');

function parseCostExpr(raw) {
    const s = String(raw).replace(/\s+/g, '');
    if (!s) return 0;
    if (/^\d+$/.test(s)) return parseInt(s, 10);
    if (!/^[\d+\-*/]+$/.test(s)) return NaN;
    return Function(`"use strict"; return (${s})`)();
}

function extractDamageFromCpp(cpp) {
    const cleaned = cpp.replace(/^#[^\n]*\n/gm, '');
    const parts = cleaned.split('{ 0, 0, (char *) 0,');
    const re =
        /\b(ILLOBJ|WEAPON|ARMOR|RING|AMULET|TOOL|FOOD|POTION|SCROLL|SPBOOK|WAND|COIN|GEM|ROCK|BALL|CHAIN|VENOM)_CLASS\s*,\s*([^,]+)\s*,\s*([^,]+)\s*,\s*(-?\d+)\s*,\s*(\d+)\s*,\s*([^,]+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,/;
    const wsdam = [];
    const wldam = [];
    for (let i = 1; i < parts.length; i++) {
        const m = parts[i].match(re);
        if (!m) {
            throw new Error(`gen_obj_oc_damage: no class match in object block ${i}`);
        }
        const sd = parseCostExpr(m[7]);
        const ld = parseCostExpr(m[8]);
        if (!Number.isFinite(sd) || !Number.isFinite(ld)) {
            throw new Error(`gen_obj_oc_damage: bad sdam/ldam in block ${i}`);
        }
        wsdam.push(sd | 0);
        wldam.push(ld | 0);
    }
    return { wsdam, wldam };
}

const cpp = execSync(
    `cd "${includeDir}" && printf '%s\\n' '#define OBJECTS_INIT' '#include "objects.h"' | cpp -I. -I.. 2>/dev/null`,
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
);
const { wsdam, wldam } = extractDamageFromCpp(cpp);

const outPath = join(root, 'js/obj_oc_damage_data.js');
const body = `// Auto-generated by tools/gen_obj_oc_damage.mjs from nethack-c/upstream/include/objects.h (OBJECTS_INIT).
// C ref: objects.c — \`objects[otyp].oc_wsdam\` / \`oc_wldam\`.
/** @type {readonly number[]} */
export const OC_WSDAM_BY_OTYP = Object.freeze(${JSON.stringify(wsdam)});

/** @type {readonly number[]} */
export const OC_WLDAM_BY_OTYP = Object.freeze(${JSON.stringify(wldam)});

/** C: objects[].oc_wsdam */
export function objectOcWsdam(otyp) {
    const a = OC_WSDAM_BY_OTYP;
    const i = otyp | 0;
    if (i < 0 || i >= a.length) return 0;
    return a[i] | 0;
}

/** C: objects[].oc_wldam */
export function objectOcWldam(otyp) {
    const a = OC_WLDAM_BY_OTYP;
    const i = otyp | 0;
    if (i < 0 || i >= a.length) return 0;
    return a[i] | 0;
}
`;
writeFileSync(outPath, body, 'utf8');
console.log(`Wrote ${outPath} (${wsdam.length} entries)`);
