#!/usr/bin/env node
/**
 * Regenerate js/obj_oc_skill_data.js from upstream objects.h (OBJECTS_INIT).
 * Keys are C objects[] indices (otyp); oclass matches nh5_objclass.js.
 * C ref: objects.c oc_skill / oc_class; weapon.c weapon_type; obj.h is_ammo.
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const includeDir = join(root, 'nethack-c/upstream/include');
const outPath = join(root, 'js/obj_oc_skill_data.js');

/** C: const.h / weapon.c — must match js/const.js P_* values. */
const P_MAP = {
    P_NONE: 0,
    P_DAGGER: 1,
    P_KNIFE: 2,
    P_AXE: 3,
    P_PICK_AXE: 4,
    P_SHORT_SWORD: 5,
    P_BROAD_SWORD: 6,
    P_LONG_SWORD: 7,
    P_TWO_HANDED_SWORD: 8,
    P_SABER: 9,
    P_CLUB: 10,
    P_MACE: 11,
    P_MORNING_STAR: 12,
    P_FLAIL: 13,
    P_HAMMER: 14,
    P_QUARTERSTAFF: 15,
    P_POLEARMS: 16,
    P_SPEAR: 17,
    P_TRIDENT: 18,
    P_LANCE: 19,
    P_BOW: 20,
    P_SLING: 21,
    P_CROSSBOW: 22,
    P_DART: 23,
    P_SHURIKEN: 24,
    P_BOOMERANG: 25,
    P_WHIP: 26,
    P_UNICORN_HORN: 27,
};

const clsNum = {
    ILLOBJ: 1,
    WEAPON: 2,
    ARMOR: 3,
    RING: 4,
    AMULET: 5,
    TOOL: 6,
    FOOD: 7,
    POTION: 8,
    SCROLL: 9,
    SPBOOK: 10,
    WAND: 11,
    COIN: 12,
    GEM: 13,
    ROCK: 14,
    BALL: 15,
    CHAIN: 16,
    VENOM: 17,
};

/** Classes exported into OC_SKILL_ROW_BY_OTYP (weapon.c / mkobj / objnam parity). */
const EXPORT_CLASSES = new Set([
    clsNum.WEAPON,
    clsNum.ARMOR,
    clsNum.TOOL,
    clsNum.GEM,
    clsNum.ROCK,
]);

function skillFromToken(tok) {
    if (!tok || tok === 'P_NONE') return 0;
    const neg = tok.startsWith('-');
    const key = neg ? tok.slice(1) : tok;
    const v = P_MAP[key];
    if (v == null) return 0;
    return neg ? -v : v;
}

function skillNameFromToken(tok) {
    if (!tok || tok === 'P_NONE') return 'NONE';
    const key = tok.replace(/^-/, '');
    return key.startsWith('P_') ? key.slice(2) : key;
}

const cpp = execSync(
    `cd "${includeDir}" && printf '%s\\n' '#define OBJECTS_INIT' '#include "objects.h"' | cpp -I. -I.. 2>/dev/null`,
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
);
const cleaned = cpp.replace(/^#[^\n]*\n/gm, '');
const parts = cleaned.split('{ 0, 0, (char *) 0,');
const classRe =
    /\b(ILLOBJ|WEAPON|ARMOR|RING|AMULET|TOOL|FOOD|POTION|SCROLL|SPBOOK|WAND|COIN|GEM|ROCK|BALL|CHAIN|VENOM)_CLASS\b/;
const skillRe =
    /(-?P_[A-Z_0-9]+)\s*,\s*\d+\s*,\s*(ILLOBJ|WEAPON|ARMOR|RING|AMULET|TOOL|FOOD|POTION|SCROLL|SPBOOK|WAND|COIN|GEM|ROCK|BALL|CHAIN|VENOM)_CLASS/;

/** @type {[number, { name: string, oclass: number, oc_skill: number }][]} */
const rows = [];

for (let i = 1; i < parts.length; i++) {
    const block = parts[i];
    const cm = block.match(classRe);
    if (!cm) continue;
    const oclass = clsNum[cm[1]];
    if (!EXPORT_CLASSES.has(oclass)) continue;
    const sm = block.match(skillRe);
    const tok = sm?.[1] ?? 'P_NONE';
    const oc_skill = skillFromToken(tok);
    const name = skillNameFromToken(tok);
    rows.push([i - 1, { name, oclass, oc_skill }]);
}

rows.sort((a, b) => a[0] - b[0]);

const lines = rows.map(
    ([otyp, r]) =>
        `  [${otyp}, { name: '${r.name}', oclass: ${r.oclass}, oc_skill: ${r.oc_skill} }],`,
);

const body = `// Auto-generated by tools/gen_obj_oc_skill_data.mjs from nethack-c/upstream/include/objects.h.
// Keys: C objects[] index (otyp). oclass: nh5_objclass.js (WEAPON=2, ARMOR=3, TOOL=6, GEM=13, ROCK=14).
/** @type {Map<number, { name: string, oclass: number, oc_skill: number }>} */
export const OC_SKILL_ROW_BY_OTYP = new Map([
${lines.join('\n')}
]);

/** C: objects[] oclass for exported rows; 0 when absent (do not use for mklev mksobj_init until floor parity verified). */
export function nh5OclassFromOcSkillMapLikeC(otyp) {
    return OC_SKILL_ROW_BY_OTYP.get(otyp | 0)?.oclass ?? 0;
}
`;

writeFileSync(outPath, body, 'utf8');
console.log(`Wrote ${outPath} (${rows.length} rows, otyp ${rows[0][0]}..${rows[rows.length - 1][0]})`);
